### ISSUE TITLE
Add ability to select scan PHY

### ISSUE THREAD

**Issue by goldwake** [NordicSemiconductor/Android-nRF-Connect#102]
**Is your feature request related to a problem? Please describe.**
When developing and testing devices using coded phy, it is difficult to check which PHY a device is advertising on. This is especially true if the device is advertising on multiple PHYs

**Describe the solution you'd like**
In the Scanner tab, it would be great to be able to select which PHY to scan on or, at a bare minimum see which PHY(s) a device is advertising on 

**Describe alternatives you've considered**
Using an NRF52840 DK and nrf connect on the PC but it doesn't seem to be supported there. Using a NRF52840 DK and scanning only on one PHY at a time then printing devices out over RTT, this is time consuming and annoying switching between PHYs

**Comment by philips77** [comment]
Don't you have this info after expanding the device row?

**Comment by goldwake** [comment]
I can see that it does but only sometimes. It seems to depend on which advertising message it receives first when the device is advertising on multiple PHYs

**Comment by philips77** [comment]
Historical advertising packets from the same device can be viewed in the Device Details screen. The main Scanner tab shows only the most recent advertising packet and refreshes every second, so some packets may be skipped.
But I understand that you may want to see only packets sent on PHY2 or PHY Coded. I'll add it to my backlog. Thanks for the feedback.

**Comment by philips77** [comment]
In 4.25.1 you may select Settings -> Scanner -> Physical Layer (PHY) to select only LE Coded. However, this seem not to work correctly on all phones. Some (most?) just use LE 1M as if no setting was set.

The new version added a filter to only show devices advertising with Advertising Extension. Perhaps this may help.
