### ISSUE TITLE
want source code for Android-nRF-Connect

### ISSUE THREAD

**Issue by majidjamhsidi** [NordicSemiconductor/Android-nRF-Connect#103]
hi guy's , why don't exist source code for Android-nRF-Connect ?????
if any body have source code please uploaded or send to my email and notify sent for me . 
thanks

**Comment by philips77** [comment]
Hi,
nRF Connect is a tool for developers, not a reference design. We do release source code for all other mobile apps, as they demonstrate how developers may use some features, how may create their own apps, etc. We also provide open source libraries for both Android and iOS. 
May I ask why do you need the source code for nRF Connect? Maybe we can help you in other way.

**Comment by philips77** [comment]
Hi,
nRF Connect is a tool for developers, not a reference design. We do release source code for all other mobile apps, as they demonstrate how developers may use some features, how may create their own apps, etc. We also provide open source libraries for both Android and iOS. 
May I ask why do you need the source code for nRF Connect? Maybe we can help you in other way.

**Comment by mnabilurrehman** [comment]
@philips77 I am developing an android app to receive data from nrf Bluetooth low energy. Can you please guide from where i can find help or any code to do so? As you also mentioned you release source code can you please share the link? Thanks

**Comment by philips77** [comment]
Have a look at nRF Blinky or nRF Toolbox on our GitHub account.

**Comment by mnabilurrehman** [comment]
Thanks
