### ISSUE TITLE
Zephyr DFU doesn't resume

### ISSUE THREAD

**Issue by nwsetec** [NordicSemiconductor/Android-nRF-Connect#104]
**Describe the bug**
If a Zephyr DFU fails at some point the DFU can't be resumed without restarting the Zephyr device.

1. start a DFU with nRFConnect App Version 4.22.3
2. kill the app once the DFU starts
3. Reopen the app and attempt to start the DFU
4. Note that DFU process fails immediately and doesn't start or resume DFU

**Expected behavior**
DFU process starts or resumes

**Versions (please complete the following information):**
 - nRFConnect App Version 4.22.3
- Zephyr device built with 1.14.0 with mcumgr 

**Additional context**
We have our own Android app that has the DFU library included and it does resume with the BLE Zephyr device used for the above issue.

**Comment by nwsetec** [comment]
I also noticed that after 'killing' the app after the DFU started the DFU will complete if left to finish.  It seems there's some process still running even though the app doesn't visually appear to be running.

**Comment by philips77** [comment]
Thanks for reporting the issue. I will investigate it. The app hasn't been updated for a while now, as I was busy with other tasks, but I'll resume working on it soon.

**Comment by philips77** [comment]
Fixed internally.
