### ISSUE TITLE
DFU duration estimate and overall average bitrate

### ISSUE THREAD

**Issue by nwsetec** [NordicSemiconductor/Android-nRF-Connect#105]
As a user I would like to see a live estimate of the DFU duration and overall average transfer bitrate (the graph is a bit coarse) while it is in progress so I can easily evaluate if the Bluetooth device I am developing for is performing well (for DFU).  

Thanks!

**Comment by philips77** [comment]
In the latest version (4.23.0) I added transfer speed in kB/s next to the percentage. This is the average speed starting from the first data byte sent to the last byte sent. It does not include the time needed for switching to bootloader and sending init packet. Also, the speed calculation may be corrupted when resuming DFU, as, as far as I remember, I use the total file length divided by the time and on resume the initial bytes sent is already a number > 0. I should fix it in some time later, but this is a bug in the DFU library.
