### ISSUE TITLE
Question about DFU

### ISSUE THREAD

**Issue by Laczen** [NordicSemiconductor/Android-nRF-Connect#106]
I am using DFU on zephyr with a custom app. From the documentation I would conclude that the image upload would send the offset when processing a hex file. From my initial test this does not
seem to be the case.

So my question is: Is the image offset as specified by the hex file removed when doing a upload over DFU ?

**Comment by philips77** [comment]
Yes. The accepted file format is a signed bin, not hex. Signing (on PC) removes the offset part from the file, as far as I know, and adds some header with magic number and signature. To verify what I'm saying please ask the question on DevZone or McuMgr Slack channel.

**Comment by Laczen** [comment]
@philips, thanks for the reply.
