### ISSUE TITLE
Custom 16-bit service/characteristic UUIDs are rendered as 128-bit base

### ISSUE THREAD

**Issue by simonratner** [NordicSemiconductor/Android-nRF-Connect#108]
**Describe the solution you'd like**

Custom 16-bit attributes to be rendered in short form, the same way as SIG-adopted attributes are, even if "unknown".

![Screenshot_20191120-210420](https://user-images.githubusercontent.com/667283/69305750-e4a44100-0bd9-11ea-848a-e87dd39b71e4.png)

**Comment by philips77** [comment]
What if you long click them and rename? Will the uuid shortener?

**Comment by simonratner** [comment]
Nope, even if i give it a custom name, it still displays the expanded base UUID.

**Comment by philips77** [comment]
Ok, I checked the code. I indeed look for the UUID in the database.

**Comment by philips77** [comment]
Fixed internally.
