### ISSUE TITLE
Automated test fails due to lack of permission

### ISSUE THREAD

**Issue by LindsayO94** [NordicSemiconductor/Android-nRF-Connect#114]
Running automated test using test.bat script - was working several months ago but after either an app or android version update, stopped working. Tried uninstalling and reinstalling the app, no change.

nRF Logger shows:

Test suite parse error (test_script.xml)
E 11:46:51.898 Parsing test suite failed:
E 11:46:51.903 /sdcard/NordicSemiconductor/Test/test_script.xml: open failed: EACCES (Permission denied)
E 11:46:51.909 open failed: EACCES (Permission denied)
E 11:46:51.924 Error while preparing result file
E 11:46:51.931 Permission denied

I removed the space in the folder name in case that was causing issues - didn't help.
The file is in the correct folder, nRF connect just can't access it. I went to the advanced permissions menu in settings and tried to give it storage permissions, but it wasn't in the list of apps I could give permissions to.

 - Android version: 10
 - Phone model Pixel 2
 - App Version 4.24.1

**Comment by LindsayO94** [comment]
Backed up to version 4.22.3 and it works fine. Also tried on another phone (android 9) and it did not work with the latest version of the app.

**Comment by philips77** [comment]
You need to change paths in the script you run to internal folder of the app. Have a look at this:
https://github.com/NordicSemiconductor/Android-nRF-Connect/blob/eaf00a8fddcbf52abb28d5d07880376d5d497885/documentation/Automated%20tests/test.bat#L150
You're using the NordicSemiconductor folder, which used to work before, but due to changes in the new Android, this won't work now.

**Comment by philips77** [comment]
Replace all occurrences of this path in the script.

**Comment by LindsayO94** [comment]
Thank you so much! Was there any change to the unbond operation in the latest releases? Doesn't seem to be working now.

**Comment by philips77** [comment]
Oh, didn't know. Unbonding was using a hidden API, perhaps it's blacklisted now and can't be used by apps. That must have come one day. Does it work for you on Android 9 and older?

**Comment by LindsayO94** [comment]
No, doesn't work on Android 10 - says "device.removeBond() (hidden)" in the log, and the test result indicates a failure during the unbond step.

This isn't too much of an issue since bonding to an already bonded device is allowed, but I'm now also experiencing issues with discover-services as well (fails the test step, but the service list printed in the log looks normal to me?).

Unbond log:
A 10:23:39.775 Starting 'Test' for 'Test Streaming a Recipe'
A 10:23:39.781 Scan for device...
V 10:23:39.790 Starting scan...
D 10:23:39.801 scanner.startScan(null, LOW_LATENCY, callback)
V 10:23:41.326 Stopping scanning...
D 10:23:41.336 scanner.stopScan(callback)
I 10:23:41.345 Device found: C3:77:9F:BE:7A:AC
A 10:23:41.352 Unbond...
V 10:23:41.360 Removing bond information...
D 10:23:41.360 device.removeBond() (hidden)
W 10:23:42.363 Connection timeout
V 10:23:42.380 Cleaning up...
W 10:23:44.395 'Test Streaming a Recipe' failed
I 10:23:44.439 Output file saved (ble_test_result.txt):

29-01-2020 10:23:39
Version: 4.24.1
Device: Pixel 2, Android version: 10 (QQ1A.200105.002)

Starting 'Test' for 'Test Streaming a Recipe'
   Scan for device...
10:23:41.317 C3:77:9F:BE:7A:AC -64 03190000020106080962652E77656C6C11FFFFFFFF03000044E700200000000078FF
   OK
   Unbond...FAIL

After removing the unbond, log with failed discover-services:
A 10:49:21.137 Starting 'Test' for 'Test Streaming a Recipe'
A 10:49:21.153 Scan for device...
V 10:49:21.167 Starting scan...
D 10:49:21.174 scanner.startScan(null, LOW_LATENCY, callback)
V 10:49:22.096 Stopping scanning...
D 10:49:22.106 scanner.stopScan(callback)
I 10:49:22.120 Device found: C3:77:9F:BE:7A:AC
A 10:49:22.126 Bond...
V 10:49:22.142 Create bond request on already bonded device...
I 10:49:22.142 Device bonded
A 10:49:22.144 Connect...
V 10:49:22.163 Connecting to C3:77:9F:BE:7A:AC...
D 10:49:22.163 gatt = device.connectGatt(autoConnect = false, TRANSPORT_LE, preferred PHY = LE 1M)
D 10:49:24.887 [Callback] Connection state changed with status: 0 and new state: CONNECTED (2)
I 10:49:24.887 Connected to C3:77:9F:BE:7A:AC
A 10:49:24.905 Refresh...
V 10:49:24.915 Refreshing device cache...
D 10:49:24.916 gatt.refresh() (hidden)
I 10:49:24.916 Cache refreshed
D 10:49:24.919 wait(1000)
I 10:49:25.719 PHY updated (TX: LE 2M, RX: LE 2M)
A 10:49:25.929 Discover-Services...
V 10:49:25.941 Discovering services...
D 10:49:25.941 gatt.discoverServices()
D 10:49:25.993 [Broadcast] Action received: android.bluetooth.device.action.BOND_STATE_CHANGED, bond state changed to: BOND_BONDING (11)
D 10:49:26.005 [Broadcast] Action received: android.bluetooth.device.action.BOND_STATE_CHANGED, bond state changed to: BOND_BONDED (12)
I 10:49:26.005 Device bonded
V 10:49:26.007 Cleaning up...
I 10:49:26.530 Connection parameters updated (interval: 7.5ms, latency: 0, timeout: 5000ms)
D 10:49:27.421 [Callback] Services discovered with status: 0
I 10:49:27.421 Services discovered
V 10:49:27.470 Generic Access (0x1800)
- Device Name [R W] (0x2A00)
- Appearance [R] (0x2A01)
- Peripheral Preferred Connection Parameters [R] (0x2A04)
- Central Address Resolution [R] (0x2AA6)
Generic Attribute (0x1801)
- Service Changed [I] (0x2A05)
   Client Characteristic Configuration (0x2902)
Unknown Service (f0a07fc9-376b-4046-8c5e-2478a594fa3a)
- Unknown Characteristic [W] (f0a07fd1-376b-4046-8c5e-2478a594fa3a)
   Characteristic User Description (0x2901)
- Unknown Characteristic [R] (f0a07fd0-376b-4046-8c5e-2478a594fa3a)
   Characteristic User Description (0x2901)
- Unknown Characteristic [R W] (f0a07fd2-376b-4046-8c5e-2478a594fa3a)
   Characteristic User Description (0x2901)
- Unknown Characteristic [R W] (f0a07fd3-376b-4046-8c5e-2478a594fa3a)
   Characteristic User Description (0x2901)
- Unknown Characteristic [R W] (f0a07fd4-376b-4046-8c5e-2478a594fa3a)
   Characteristic User Description (0x2901)
- Unknown Characteristic [R W] (f0a07fd5-376b-4046-8c5e-2478a594fa3a)
   Characteristic User Description (0x2901)
Unknown Service (73fee136-61d0-44d6-84f8-c11c60245d50)
- Unknown Characteristic [N R] (73fee137-61d0-44d6-84f8-c11c60245d50)
   Client Characteristic Configuration (0x2902)
   Characteristic User Description (0x2901)
- Unknown Characteristic [R] (73fee138-61d0-44d6-84f8-c11c60245d50)
   Characteristic User Description (0x2901)
Unknown Service (e3b982d2-8d6f-4ca6-a5ad-79c05e6f6586)
- Unknown Characteristic [N R W] (e3b982d3-8d6f-4ca6-a5ad-79c05e6f6586)
   Client Characteristic Configuration (0x2902)
   Characteristic User Description (0x2901)
- Unknown Characteristic [N R] (e3b982d4-8d6f-4ca6-a5ad-79c05e6f6586)
   Client Characteristic Configuration (0x2902)
   Characteristic User Description (0x2901)
Unknown Service (9424002c-38ea-4329-8b06-66e441d00504)
- Unknown Characteristic [W] (9424002d-38ea-4329-8b06-66e441d00504)
   Characteristic User Description (0x2901)
Unknown Service (f89407d8-6b00-413e-9c39-1ba7b312ff37)
- Unknown Characteristic [W] (f89407d9-6b00-413e-9c39-1ba7b312ff37)
   Characteristic User Description (0x2901)
- Unknown Characteristic [N R] (f89407da-6b00-413e-9c39-1ba7b312ff37)
   Client Characteristic Configuration (0x2902)
   Characteristic User Description (0x2901)
Unknown Service (d5e9dea4-720e-4aa6-b5d1-9f528baf4f25)
- Unknown Characteristic [W] (d5e9dea5-720e-4aa6-b5d1-9f528baf4f25)
   Characteristic User Description (0x2901)
D 10:49:27.470 gatt.setCharacteristicNotification(00002a05-0000-1000-8000-00805f9b34fb, true)
D 10:49:27.473 gatt.setCharacteristicNotification(73fee137-61d0-44d6-84f8-c11c60245d50, true)
D 10:49:27.474 gatt.setCharacteristicNotification(e3b982d3-8d6f-4ca6-a5ad-79c05e6f6586, true)
D 10:49:27.475 gatt.setCharacteristicNotification(e3b982d4-8d6f-4ca6-a5ad-79c05e6f6586, true)
D 10:49:27.476 gatt.setCharacteristicNotification(f89407da-6b00-413e-9c39-1ba7b312ff37, true)
I 10:49:27.515 Connection parameters updated (interval: 45.0ms, latency: 0, timeout: 5000ms)
V 10:49:28.025 Disconnecting...
D 10:49:28.025 gatt.disconnect()
D 10:49:28.063 [Callback] Connection state changed with status: 0 and new state: DISCONNECTED (0)
I 10:49:28.063 Disconnected
D 10:49:28.063 gatt.close()
D 10:49:28.075 wait(200)
W 10:49:28.286 'Test Streaming a Recipe' failed
I 10:49:28.350 Output file saved (ble_test_result.txt):

29-01-2020 10:49:21
Version: 4.24.1
Device: Pixel 2, Android version: 10 (QQ1A.200105.002)

Starting 'Test' for 'Test Streaming a Recipe'
   Scan for device...
10:49:22.092 C3:77:9F:BE:7A:AC -63 03190000020106080962652E77656C6C11FFFFFFFF03000044E700200000000078FF
   OK
   Bond...OK
   Connect...OK
   Refresh...OK
   Discover-Services...FAIL

**Comment by LindsayO94** [comment]
Ah, I think the test was cleaning up too quickly. Adding a sleep at the end fixed this issue.

**Comment by philips77** [comment]
Does the service discovery fails on timeout? Try extending it by setting timeout parameter.

**Comment by LindsayO94** [comment]
As far as I can tell, no. I extended it to 10 seconds (which is far longer than it takes, looking at the log timestamps) and this issue still happens intermittently. I am curious why the test seems to want to clean up before the results from the service discovery are printed. I'm also curious why it says that the device is already bonded and then seems to go through bonding anyway.

A 10:49:22.126 Bond...
V 10:49:22.142 Create bond request on already bonded device...
**I 10:49:22.142 Device bonded**
A 10:49:22.144 Connect...
V 10:49:22.163 Connecting to C3:77:9F:BE:7A:AC...
D 10:49:22.163 gatt = device.connectGatt(autoConnect = false, TRANSPORT_LE, preferred PHY = LE 1M)
D 10:49:24.887 [Callback] Connection state changed with status: 0 and new state: CONNECTED (2)
I 10:49:24.887 Connected to C3:77:9F:BE:7A:AC
A 10:49:24.905 Refresh...
V 10:49:24.915 Refreshing device cache...
D 10:49:24.916 gatt.refresh() (hidden)
I 10:49:24.916 Cache refreshed
D 10:49:24.919 wait(1000)
I 10:49:25.719 PHY updated (TX: LE 2M, RX: LE 2M)
A 10:49:25.929 Discover-Services...
V 10:49:25.941 Discovering services...
D 10:49:25.941 gatt.discoverServices()
**D 10:49:25.993 [Broadcast] Action received: android.bluetooth.device.action.BOND_STATE_CHANGED, bond state changed to: BOND_BONDING (11)
D 10:49:26.005 [Broadcast] Action received: android.bluetooth.device.action.BOND_STATE_CHANGED, bond state changed to: BOND_BONDED (12)
I 10:49:26.005 Device bonded**
V 10:49:26.007 Cleaning up...

**Comment by philips77** [comment]
Ok, I know what's going on. This seems to be an issue in nRF Connect. 
When the bond state changes to BONDED, an internal method `operationCompleted()` is called. At that moment, the service discovery is waiting for operation to finish, so at this moment is resumes. However, services are still `null`, so service discovery thinks it has failed. I have to add a flag indicating that bonding wasn't requested, so operation should not be mark as completed. I will address it in the next release, but I can't promise any date now.

**Comment by philips77** [comment]
Hi, could you check if the attached version fixes the issue with service discovery?
[nRF Connect 4.24.1-fixed.apk.zip](https://github.com/NordicSemiconductor/Android-nRF-Connect/files/4133615/nRF.Connect.4.24.1-fixed.apk.zip)
That was a quick fix, but I didn't test it in any way.

**Comment by LindsayO94** [comment]
I did get a "GATT ERROR" when trying to connect during one run, but other than that it seems to be working well! May have just been human error, perhaps I reset the device too late and it was in the middle of connecting.
