### ISSUE TITLE
Size of Byte Array Defaults to 18 Bytes if the Actual Size is Bigger Than 20 Bytes

### ISSUE THREAD

**Issue by TheFrozenDuck** [NordicSemiconductor/Android-nRF-Connect#115]
**Describe the bug**
When trying to write a value as a byte array larger than 20 bytes, only the first 18 bytes get transmitted to the peripheral.

**To Reproduce**
1. Connect to a BLE device
2. Click on the "upload" button to open the "Write Value" dialog
3. Choose "Byte Array" as value type
4. Enter a value longer than 20 bytes
5. View the data received by a peripheral (serial, etc.), showing only 18 bytes of the byte array having arrived

**Expected behavior**
The MTU normally is 20 bytes on Android. So atleast the first 20 bytes should be sent. Additionally, following solutions should be considered:
- offer the option to send the rest of the byte array
- show a warning (Android Toast, etc.) that only a certain size can be transmitted

**Screenshots**
n/a

**Versions (please complete the following information):**
 - Android version: 10
 - Phone model: Google Pixel 3XL
 - App Version: 4.24.1

**Additional context**
n/a

**Comment by philips77** [comment]
It looks like you are trying to send more than 20 bytes. If MTU is set to 23, the maximum payload size is 20 bytes. 3 bytes are used for handle number (2) and opcode (1).
When you try sending more than MTU-3 bytes using Write Request type (aka Write With Response or WRITE_DEFAULT  on Android), the system is automatically using Long Write Procedure (aka Queued Write). In Long Write procedure payload is split into multiple packets, each maximum 18 bytes (2 bytes are used for offset). First n-1 packets sent are Prepare Write Request followed by Execute Write Request, which contains a flag: execute or cancel. If the device does not support Long Write (a buffer is required to store not executed data), it may send an error and the write request will be cancelled. You actually should not receive those 18 bytes at all in your app, as it has been cancelled, after all, so stack should disregard them.
![obraz](https://user-images.githubusercontent.com/6576580/73522636-2f77db80-4409-11ea-98ee-00932dfb9a96.png)
Here's a screenshot from a sniffer. The device (uart sample from Nordic SDK 16) rejects Long Write by sending error 0x80. The error code seems invalid, but nevertheless Android cancels write.

Write Command (aka Write Without Response) is only able to send MTU-3 bytes. Long Write is not possible. In nRF Connect, even if you have longer packet, it will be trimmed to fit the package. To switch write type click the arrow next to Advanced on the "Write Value" dialog.

**Comment by TheFrozenDuck** [comment]
Thank you for the information. I'll close this ticket.
