### ISSUE TITLE
RSSI monitor chart (Scanner) X-axis values not visible

### ISSUE THREAD

**Issue by wbidus** [NordicSemiconductor/Android-nRF-Connect#118]
**Describe the bug**
When using Light theme, X-axis values of the RSSI monitor chart are not visible. They are visible in Dark theme (white font on black background), so i suspect that light mode may be using white font on white background.

**To Reproduce**
1. Go to Settings
2. Click on Theme
3. Select Light
4. Restart app
5. Open SCANNER tab
6. Swipe left->right to open RSSI monitor chart
7. Look on the chart. Y-axis values (dBm numbers) are visible. X-axis values (elapsed s) are not.
8. Repeat steps 1-4, but in 3 select Dark. Restart app, check chart again. X-axis is labeled fine.

**Expected behavior**
I expect X-axis values to be visible in RSSI monitor chart.

**Screenshots**
Light theme shows problem, Dark theme is fine.
![Screenshot_2020-03-24-17-06-51-526_no nordicsemi android mcp](https://user-images.githubusercontent.com/11584978/77451486-0403e280-6df5-11ea-8e3b-e8c93cc08f3d.jpg)
![Screenshot_2020-03-23-10-27-46-531_no nordicsemi android mcp](https://user-images.githubusercontent.com/11584978/77451488-05cda600-6df5-11ea-9f04-bfda89de0a78.jpg)

**Versions (please complete the following information):**
 - Android version: 10
 - Phone model: Xiaomi Mi9
 - App Version 4.24.1

**Comment by philips77** [comment]
Nice one! 
Consider it fixed in the next release. Thanks!

**Comment by philips77** [comment]
Fixed internally.
