### ISSUE TITLE
How to send all services and characteristics by email ?

### ISSUE THREAD

**Issue by nbenm** [NordicSemiconductor/Android-nRF-Connect#119]
Hi,

This is just a question.
I would like to share via email all services and characteristics at once.
How can I do this.
I can only select and send them one by one.

Thanks

**Comment by philips77** [comment]
You can either share the log, services are logged on verbose level, or click clone services to get them imported to the gatt server configuration, form where you can export all as XML.

**Comment by nbenm** [comment]
Thank you very much.
