### ISSUE TITLE
Is there a way to know the handle?

### ISSUE THREAD

**Issue by nbenm** [NordicSemiconductor/Android-nRF-Connect#120]
This is also a question, not an issue.
Is there a way to know the handle?
Thanks in advance.

**Comment by philips77** [comment]
There's a method called [getInstanceId()](https://developer.android.com/reference/android/bluetooth/BluetoothGattService#getInstanceId()) in `BluetoothGattService` and `BluetoothGattCharacteristic`. They used to return 0-based index before Android 6, and later they seemed to return the handle number. However, this is not documented, therefore this behavior may change in the future, if it hasn't already (I didn't check recently). Also, in`BluetoothGattDescriptor` this method is [hidden](https://android.googlesource.com/platform/frameworks/base/+/76c1d9d5e15f48e54fc810c3efb683a0c5fd14b0/core/java/android/bluetooth/BluetoothGattDescriptor.java#236), for some reason, so you'd need to use reflections. 

Therefore, in nRF Connect we don't show this value.
