### ISSUE TITLE
CGM Status Cal/Temp info disaplay error

### ISSUE THREAD

**Issue by lijinqiu1** [NordicSemiconductor/Android-nRF-Connect#124]
CSM Measurement service

the Cal/Temp info feild 
when set "Calibration Recommended" bit 1 ,it is display both
"Calibration Recommended" and "Calibration Required".
When set the "Calibration Required" bit 1, it is disaplay "Sensor Temperature too high"!
![image](https://user-images.githubusercontent.com/22447898/79822852-bfa03e00-83c4-11ea-9c59-16448d1bc8e5.png)

**Comment by philips77** [comment]
Thank you for the report. I'll address it in the next release.

**Comment by philips77** [comment]
Fixed internally. Thank you for creating the issue.
