### ISSUE TITLE
A little confused  about the connect button display

### ISSUE THREAD

**Issue by BaiduSu** [NordicSemiconductor/Android-nRF-Connect#127]
I had install this nRF connect android app, it can list all scanned devices, but some devices have a CONNECT button, some devices do not have this button. I hope to learn about how to distinguish whether the device can be connected, and then show a CONNECT button. Thanks !!!

**Comment by philips77** [comment]
The app is using this method: https://developer.android.com/reference/android/bluetooth/le/ScanResult#isConnectable(), available since Android 8. Prior to Oreo, all devices have Connect button, but for some connection will fail.
