### ISSUE TITLE
Is there a source code for Android apps?

### ISSUE THREAD

**Issue by hjh2881** [NordicSemiconductor/Android-nRF-Connect#128]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by philips77** [comment]
No, the app is not open sourced.
It's written on Readme: https://github.com/NordicSemiconductor/Android-nRF-Connect#application
Duplicate of #1, #49, #53, #96, #103.

**Comment by philips77** [comment]
We have open sourced our other [Android](https://github.com/NordicSemiconductor?q=android&type=&language=) and [iOS](https://github.com/NordicSemiconductor?q=IOS&type=&language=) apps.

**Comment by hjh2881** [comment]
Thank you very much.
