### ISSUE TITLE
Different LESC operation for each smartphone

### ISSUE THREAD

**Issue by YoungSooBae1224** [NordicSemiconductor/Android-nRF-Connect#132]
**Describe the bug**
Not support to fix out-of-sync bonding programmatically for each smartphone.

**To Reproduce**
1. Setting Whitelist and max number of bonded peer is 1.
2. Connect to nRF52832 and smartphone.(LE secure)
3. Disconnect.
4. Remove bonded in nRF52832
5. Reconnect to nRF52832 and smartphone. but no out-of-sync bonding correction.(LE secure)

**Expected behavior**
fix out-of-sync bonding(No problem with Samsung Galaxy Tab S3)

**Screenshots**
n/a

**Versions (please complete the following information):**
 - Android version: 10
 - Phone model: Pixel 3a/Pixel3XL
 - App Version 4.24.2

 - Android version: 9
 - Phone model: Samsung Galaxy A20/HW-02L
 - App Version 4.24.2

**Additional context**
fix has occurred In nRFToolbox.
and The pairing process was only performed when the Notification button was pressed.

I attach two log.
The same test, but Pixel smartphones are not broadcasting the following:
```
D	15:56:15.390	[Broadcast] Action received: android.bluetooth.device.action.BOND_STATE_CHANGED, bond state changed to: BOND_BONDING (11)
D	15:56:15.430	[Broadcast] Action received: android.bluetooth.device.action.PAIRING_REQUEST, pairing variant: PAIRING_VARIANT_CONSENT (3)
```
[not_occur_fix-out-of-sync_bonding.txt](https://github.com/NordicSemiconductor/Android-nRF-Connect/files/5154585/not_occur_fix-out-of-sync_bonding.txt)
[occur_fix-out-of-sync_bonding.txt](https://github.com/NordicSemiconductor/Android-nRF-Connect/files/5154586/occur_fix-out-of-sync_bonding.txt)

**Comment by philips77** [comment]
Hello, sorry for super long delay. I was busy with other tasks. Yesterday passed 2 years since the issue was created. Congratulations 🥳 
Bonding is managed by the operating system. There's nothing we can do. Sorry!
