### ISSUE TITLE
How to send an integer from Android app to BLE device using writeCharacteristic?

### ISSUE THREAD

**Issue by n-maiya** [NordicSemiconductor/Android-nRF-Connect#140]
I'm getting error code 13 which is invalid attribute length. I just need to send an integer value from my phone to a nRF52 over BLE.

**Comment by philips77** [comment]
Hello,
You need to know what is the fw on the nRF52 expecting. An integer can be sent as unsigned or signed int with 8, 16 or 32 bits, in Little or Big Endian. The returned error also depends on your fw implementation.
The custom write dialog allows you to select the value type.
