### ISSUE TITLE
About Advertiser Manufacturer Data

### ISSUE THREAD

**Issue by BIGMONK** [NordicSemiconductor/Android-nRF-Connect#141]
**Describe the bug**
Anyone can tell me how to fill it?
The OK button won't be enabled no matter what I do

![image](https://user-images.githubusercontent.com/18308637/101619387-2ce50a00-3a4e-11eb-98c0-afa7b83fe949.png)

**Comment by roshanrajaratnam** [comment]
HI @BIGMONK  if you enter the company identifier which is a 16-bit or 2-octet value and some data it should enable the ok button.

**Comment by BIGMONK** [comment]
> HI @BIGMONK if you enter the company identifier which is a 16-bit or 2-octet value and some data it should enable the ok button. Company identifier is a Bluetooth SIG Defined value, for example identifier for Nordic Semiconductor is 0x0059.

Thank you very much
