### ISSUE TITLE
Bluetooth Phone devices not being discovered by the app

### ISSUE THREAD

**Issue by vasilje** [NordicSemiconductor/Android-nRF-Connect#143]
**Problem description**
In Bluetooth settings I can see that the device is available and that I can pair with it, however nRF Connect doesnt show this device in the Scanner section. 

**To Reproduce**
I was testing with phones Xiaomi Mi Mix 2s, Samsung Galaxy S7 and Xiaomi Mi 9.

**Comment by philips77** [comment]
nRF Connect lists only Bluetooth Low Energy devices. Perhaps the one you have is using standard Bluetooth.
