### ISSUE TITLE
about BLE 5.0 extented advertisement and connect

### ISSUE THREAD

**Issue by ArthurHCL** [NordicSemiconductor/Android-nRF-Connect#146]
my BLE slaver device uses coded PHY(125K)，advertisement include primary and secondory channel，and APP can resolve them correctly。but when I click "connect"，no any response。is APP does not support connect?(ADV_EXT_IND and AUX_ADV_IND)

**Comment by philips77** [comment]
It's about whether your phone can. The app just calls an API method to connect. 
I don't know what phone are you using and why it does not connect.
