### ISSUE TITLE
Connect button is shown for a nonconnectable beacon.

### ISSUE THREAD

**Issue by eugmes** [NordicSemiconductor/Android-nRF-Connect#147]
**Describe the bug**
A "connect" button is show in the UI for a nonconnectable beacon (beacon sample from Zephyr/NCS). Pressing this button results in a connection attempt that never completes.

**To Reproduce**
1. Build and flash `beacon` bluetooth sample from Zephyr or NCS.
2. Start nRF Connect app and find the device.
3. Observe the connect button.

**Expected behavior**
No connect button is show for a nonconnectable device.

**Screenshots**
![Screenshot_20210512-144645](https://user-images.githubusercontent.com/447040/117977356-03981500-b331-11eb-8a4e-838949ebf55d.png)

**Versions (please complete the following information):**
 - Android version: 9
 - Phone model Nokia 8
 - App Version 4.23.3 (according to the changelog on Google Play, where to find this info in the application itself?)

**Additional context**
A modified `central` sample shows advertisement as nonconnectable.

**Comment by philips77** [comment]
Hello @eugmes,
The device must have been connectable at least once since you refreshed the list of devices. That's not an issue, it's by design. Also, before Android 8 all devices have Connect button, as this info want available before that.
