### ISSUE TITLE
When I create an Advertiser, other devices still scan the real Bluetooth address

### ISSUE THREAD

**Issue by lhn0610** [NordicSemiconductor/Android-nRF-Connect#151]
**Describe the bug**
Create an Advertiser, other devices still scan the real Bluetooth address.

**To Reproduce**
1. Go to 'Advertiser'
2. Click on 'add advertiser'
3. Click on 'enable'

**Expected behavior**
other devices scan the random Bluetooth address.

**Screenshots**
none

**Versions (please complete the following information):**
 - Android version: [e.g. 8.0.0]
 - Phone model [e.g. Samsung]
 - App Version [e.g. 4.24.3]

**Additional context**

**Comment by philips77** [comment]
Starting from Android 5, as far as I remember, Android is using random address when advertising, and is changing the address every few minutes. This may not work on some phones, but there's nothing we can do in the nRF Connect app to change it.

**Comment by lhn0610** [comment]
Thanks！
