### ISSUE TITLE
SecurityException crash during automated tests

### ISSUE THREAD

**Issue by Bernstern** [NordicSemiconductor/Android-nRF-Connect#154]
**Describe the bug**
nRF Connect crashes after a `java.lang.SecurityException` is raised during an automated test. We haven't found a way to trigger it with a command in the automated tests or a set of steps to trigger it, but after the recent updates we have been seeing this crash more often. 

We submitted feedback w/ the crash through Androids crash feedback. We can update this issue if we find steps to reliably reproduce. 

**To Reproduce**
1. Running automated tests in succession
2. Seems to more happen when the disconnect command is invoked

**Expected behavior**
NA

**Screenshots**
NA

**Versions (please complete the following information):**
 - Android version: 8.0.0
 - Phone model: Pixel 2
 - App Version 4.24.3

**Additional context**
From the android crash log:
```
Source class: android.os.Parcel
Source method: readException
Line number: 1943
```
The frames in the stack trace with nordic code were:
```
no.nordicsemi.android.mcp.util.FileHelper.getContentUri(:3)
no.nordicsemi.android.mcp.test.TestService.onHandleIntent(:60)
```

**Comment by philips77** [comment]
Thank you for the report. We're preparing a new release, I'll make sure it's fixed.

**Comment by philips77** [comment]
Hello, could you try it on the new 4.25.1 version?

**Comment by philips77** [comment]
I'm closing, assuming it's fixed. Also, I'm releasing 4.25.4 which fixed Automated Tests on Android 13.
