### ISSUE TITLE
Disconnect happens Error 22 (0x16): GATT CONN TERMINATE LOCAL HOST during Automated tests

### ISSUE THREAD

**Issue by royan-hub** [NordicSemiconductor/Android-nRF-Connect#161]
**Describe the bug**
During automated tests, when executing disconnect，it displays Error 22 (0x16): GATT CONN TERMINATE LOCAL HOST on phone, but it won't happen when I manually disconnect, it also display disconnecting... and gatt.disconnect()

**To Reproduce**
1. Running automated tests successfully
2. when executing disconnect, it displays Error 22 (0x16): GATT CONN TERMINATE LOCAL HOST on phone
3. when repeatedly setup connect and disconnect, the last disconnect will not work on phone

**Versions (please complete the following information):**
 - Android version: [e.g. 9.0.0]
 - Phone model [e.g. 红米10X]
 - App Version [e.g. 4.24.3]

**Comment by philips77** [comment]
The error 22 is reported when the phone disconnects, but the disconnection wasn't initiated nay the user (`gatt.disconnect()`). In the latter case the status is 0 (success).

**Comment by royan-hub** [comment]
So how can I eliminate this error 22?

**Comment by royan-hub** [comment]
We want to automated test is the same as manual test, 
for automated test, our xml :
![xml](https://user-images.githubusercontent.com/73638439/158732019-421f01fd-f884-4c4c-bf7a-82164fdc9af6.PNG)
and when we execute the xml file, the phone display:
![IMG20220315151144(1)](https://user-images.githubusercontent.com/73638439/158732203-86f0a4e3-8124-4682-92f3-2d7094e8d87d.jpg)
