### ISSUE TITLE
Source code or tutorial for BLE advertise function.

### ISSUE THREAD

**Issue by ShikamaruBH** [NordicSemiconductor/Android-nRF-Connect#171]
May I have the source code for the BLE advertise function ? Or perhaps a tutorial about it, I've tried all tutorial I could on the internet but they not work (relate about BLUETOOTH_ADVERTISE permission is denied).
Please help, thanks !

**Comment by philips77** [comment]
From Android 12 you need to request `BLUETOOTH_ADVERTISE` permission in run-time. Here's how you do it: https://developer.android.com/training/permissions/requesting#request-permission
Then, follow: https://developer.android.com/reference/android/bluetooth/le/BluetoothLeAdvertiser
