### ISSUE TITLE
Decoding of CGM Measurement Packet is Incorrect

### ISSUE THREAD

**Issue by dfridley-roche** [NordicSemiconductor/Android-nRF-Connect#174]
**Describe the bug**
Decoding of CGM Measurement Packet is incorrect.

**To Reproduce**
1. Connect to a CGMS device that is sending CGM Measurement packets with annunciations and one or more optional fields.
2. Subscribe to CGM Measurements

**Expected behavior**
Decoding of the packet should show annunciation flags set and correct Trend, Quality, E2E-CRC values

For example.
Data packet:
`0D-43-73-00-2C-01-03-24-00-1A-00-3E-04`

Should decode as:
```
Glucose concentration: 115.0 mg/dL
Sequence number: 300 (Time Offset in min)
 Cal/Temp Info:
- Time Synchronization Required
- Calibration Not Allowed
Trend: 36.0 mg/dL/min
Quality: 26.0%
E2E-CRC: 0x043E
```
**Screenshots**
Incorrect decoding of CGM Measurement Packet
![nRF-CgmMeasurementPacket-IncorrectDecoding](https://user-images.githubusercontent.com/68288575/177011473-eea311da-7807-4198-bc3d-7902c4898e6d.png)

**Versions (please complete the following information):**
 - Android version: 12
 - Phone model Pixel 5
 - App Version 4.25.3

**Additional context**
See Bluetooth 
[Gatt Specification Supplement 6](https://www.bluetooth.com/specifications/specs/gatt-specification-supplement-6/) section _CGM Measurement_

**Comment by philips77** [comment]
Thanks! We'll fix it in the next release.

**Comment by philips77** [comment]
Fixed internally.
