### ISSUE TITLE
not able to access XML file 

### ISSUE THREAD

**Issue by Bhawnakrsingh** [NordicSemiconductor/Android-nRF-Connect#179]
**Describe the bug**
I m trying to call xml file in rooted android device but getting error (Test suit file not found in Test/file.xml)
wont be able to access xml file from that path.

**To Reproduce**
1.installed nrf app in device.
2.Connect your Android device to the PC, enable USB debugging on it and install required drivers and ADB on the PC
3. push xml file to that path 
4. called test.bat file to run xml file.

**Expected behavior**
trying to execute  sample testcase,

**Screenshots**
<img width="221" alt="image" src="https://user-images.githubusercontent.com/31128355/191506183-ab5ed701-fc95-4962-973b-bb6459f348d9.png">

**Versions (please complete the following information):**
 - Android version: 12
 - Phone model - android board
 - App Version 4,26.0
 please help to resolve this issue @philips77

**Comment by philips77** [comment]
Hello,

Have a look at the script:
https://github.com/NordicSemiconductor/Android-nRF-Connect/blob/f10b32bd7ff1cda0866512a7c30ce3accbc0bb1b/documentation/Automated%20tests/test.bat#L155
It copies the XML file to a private folder of the app on external storage. This is the only place where an app has access without using write permission, and is also accessible using `adb`.  

Have you modified the script to have only *Test* folder?

**Comment by Bhawnakrsingh** [comment]
Thanks
