### ISSUE TITLE
how to add a new GATT service using xml.

### ISSUE THREAD

**Issue by Bhawnakrsingh** [NordicSemiconductor/Android-nRF-Connect#183]
using XML Approach  how can we add new service in GATT
can u please help on this @philips77

**Comment by philips77** [comment]
In the app open the hamburger menu, select Configure GATT Server.
Click the drop down menu at the top and select the icon with an arrow pointing down (Import). Select the XML with server configuration. You may get the XML by exporting the configuration file from another Android device.
