### ISSUE TITLE
NRF Connect App is the only app that can scan Coded PHY BT on my custom made sensor. I would like to know how.

### ISSUE THREAD

**Issue by racketry** [NordicSemiconductor/Android-nRF-Connect#187]
Hi,

I made a custom IoT device with nrf52833 module on it and configured the Coded PHY layer for BT.

Interestingly, I can only SCAN this device with NRF Connect App (on Samsung S20 phone), other apps, my custom apps, os scan don't seem to work.

Libraries I tried:
 - RxAndroidBle,
 - SweetBlue
 - Nordic's Android-BLE-Library
 - Stock Android aproach

Nothing seems to work.

Sinced this is a closed source app I would like to know if there is some "special sauce" to it?

**Comment by philips77** [comment]
Hello,
As this is regarding scanning, the Android BLE Library is not relevant here. Perhaps you meant Scanner Compat Library instead.
To scan Coded PHY devices you need to set:
* [`setLegacy(false)`](https://developer.android.com/reference/android/bluetooth/le/ScanSettings.Builder#setLegacy(boolean))
* [`setPhy(ScanSettings.PHY_LE_ALL_SUPPORTED)`](https://developer.android.com/reference/android/bluetooth/le/ScanSettings.Builder#setPhy(int))

and that should be enough.
Perhaps also
* [`setReportDelay(0)`](https://developer.android.com/reference/android/bluetooth/le/ScanSettings.Builder#setReportDelay(long))
* [`setScanMode(ScanSettings.SCAN_MODE_LOW_POWER)`](https://developer.android.com/reference/android/bluetooth/le/ScanSettings.Builder#setScanMode(int))

Also, mind that not all phones claiming Coded PHY support can scan for such devices on Primary PHY. The list is here (you may update): https://github.com/NordicSemiconductor/Android-BLE-Library/issues/166
