### ISSUE TITLE
一直无法升级，一直断开

### ISSUE THREAD

**Issue by rayzeng0221** [NordicSemiconductor/Android-nRF-Connect#188]
我开始使用的是 4.24.1版本，能够正常进行OTA 升级，当我把你们APP 升级到  4.26.0  之后 就一直无法成功升级了，一直升级一直断开

**Comment by rayzeng0221** [comment]
nRF Connect, 2023-02-14
S1 (88:22:B2:07:21:B1)
V	16:40:20.784	Connecting to 88:22:B2:07:21:B1...
D	16:40:20.784	gatt = device.connectGatt(autoConnect = false, TRANSPORT_LE, preferred PHY = LE 1M)
D	16:40:21.566	[Callback] Connection state changed with status: 133 and new state: DISCONNECTED (0)
E	16:40:21.566	Error 133 (0x85): GATT ERROR
I	16:40:21.566	Disconnected
D	16:40:33.680	gatt.close()
D	16:40:33.683	wait(200)
V	16:40:33.883	Connecting to 88:22:B2:07:21:B1...
D	16:40:33.883	gatt = device.connectGatt(autoConnect = false, TRANSPORT_LE, preferred PHY = LE 1M)
D	16:40:34.671	[Broadcast] Action received: android.bluetooth.device.action.ACL_CONNECTED
D	16:40:34.677	[Callback] Connection state changed with status: 0 and new state: CONNECTED (2)
I	16:40:34.677	Connected to 88:22:B2:07:21:B1
V	16:40:34.682	Discovering services...
D	16:40:34.682	gatt.discoverServices()
I	16:40:34.971	Connection parameters updated (interval: 7.5ms, latency: 0, timeout: 5000ms)
D	16:40:35.492	[Callback] Services discovered with status: 0
I	16:40:35.492	Services discovered
V	16:40:35.508	Generic Access (0x1800)
- Device Name [R] (0x2A00)
- Appearance [R] (0x2A01)
- Peripheral Preferred Connection Parameters [R] (0x2A04)
Generic Attribute (0x1801)
- Service Changed [I] (0x2A05)
   Client Characteristic Configuration (0x2902)
Nordic UART Service (6e400001-b5a3-f393-e0a9-e50e24dcca9e)
- TX Characteristic [N] (6e400003-b5a3-f393-e0a9-e50e24dcca9e)
   Client Characteristic Configuration (0x2902)
- RX Characteristic [WNR] (6e400002-b5a3-f393-e0a9-e50e24dcca9e)
Device Information (0x180A)
- System ID [R] (0x2A23)
- Model Number String [R] (0x2A24)
- Serial Number String [R] (0x2A25)
- Firmware Revision String [R] (0x2A26)
- Hardware Revision String [R] (0x2A27)
- Software Revision String [R] (0x2A28)
- Manufacturer Name String [R] (0x2A29)
- IEEE 11073-20601 Regulatory Certification Data List [R] (0x2A2A)
- PnP ID [R] (0x2A50)
Device Firmware Update Service (00001530-1212-efde-1523-785feabcd123)
- DFU Control Point [N W] (00001531-1212-efde-1523-785feabcd123)
   Client Characteristic Configuration (0x2902)
- DFU Packet [WNR] (00001532-1212-efde-1523-785feabcd123)
- DFU Version [R] (00001534-1212-efde-1523-785feabcd123)
D	16:40:35.508	gatt.setCharacteristicNotification(00002a05-0000-1000-8000-00805f9b34fb, true)
D	16:40:35.510	gatt.setCharacteristicNotification(6e400003-b5a3-f393-e0a9-e50e24dcca9e, true)
I	16:40:35.553	Connection parameters updated (interval: 45.0ms, latency: 0, timeout: 5000ms)
V	16:40:52.731	[DFU] DFU service started
V	16:40:52.731	[DFU] Opening file...
I	16:40:52.746	[DFU] Firmware file opened successfully
V	16:40:52.748	[DFU] Connecting to DFU target...
D	16:40:52.748	[DFU] gatt = device.connectGatt(autoConnect = false, TRANSPORT_LE, preferredPhy = LE_1M | LE_2M)
I	16:40:52.761	[DFU] Connected to 88:22:B2:07:21:B1
V	16:40:52.762	[DFU] Discovering services...
D	16:40:52.762	[DFU] gatt.discoverServices()
I	16:40:52.766	[DFU] Services discovered
D	16:40:52.779	[DFU] wait(1000)
V	16:40:53.780	[DFU] Reading DFU version number...
D	16:40:53.780	[DFU] gatt.readCharacteristic(00001534-1212-efde-1523-785feabcd123)
I	16:40:53.872	[DFU] Read Response received from 00001534-1212-efde-1523-785feabcd123, value (0x): 00-01
A	16:40:53.872	[DFU] Version number read: 1.0
V	16:40:53.874	[DFU] Requesting new MTU...
D	16:40:53.874	[DFU] gatt.requestMtu(517)
I	16:40:54.052	[DFU] MTU changed to: 247
D	16:40:54.053	[DFU] wait(1000)
V	16:40:55.054	[DFU] Enabling notifications for 00001531-1212-efde-1523-785feabcd123
D	16:40:55.054	[DFU] gatt.setCharacteristicNotification(00001531-1212-efde-1523-785feabcd123, true)
D	16:40:55.056	[DFU] gatt.writeDescriptor(00002902-0000-1000-8000-00805f9b34fb, value=0x01-00)
I	16:40:55.176	[DFU] Data written to descr.00001531-1212-efde-1523-785feabcd123, value (0x): 01-00
V	16:40:55.176	[DFU] Notifications enabled for 00001531-1212-efde-1523-785feabcd123
A	16:40:55.176	[DFU] Notifications enabled
D	16:40:55.176	[DFU] wait(1000)
V	16:40:56.177	[DFU] Writing to characteristic 00001531-1212-efde-1523-785feabcd123
D	16:40:56.177	[DFU] gatt.writeCharacteristic(00001531-1212-efde-1523-785feabcd123)
I	16:40:56.393	[DFU] Data written to 00001531-1212-efde-1523-785feabcd123, value (0x): 01-04
A	16:40:56.394	[DFU] DFU Start sent (Op Code = 1, Upload Mode = 4)
V	16:40:56.394	[DFU] Writing to characteristic 00001532-1212-efde-1523-785feabcd123
D	16:40:56.395	[DFU] gatt.writeCharacteristic(00001532-1212-efde-1523-785feabcd123)
I	16

**Comment by philips77** [comment]
您可以粘贴其余的日志吗？

**Comment by rayzeng0221** [comment]
> 您可以粘贴其余的日志吗？

我是直接在你们APP 的 点击 show log，然后最下边的 点击复制出来的  这是全部了。然后我还发现了，从你们2022年发布的第一个版本开始就不嫩恶搞正常升级了  2022年之前的版本都可以正常升级。

**Comment by rayzeng0221** [comment]
![21676365313_ pic](https://user-images.githubusercontent.com/16337418/218692047-8562c455-9646-4022-a48c-f6844430648f.jpg)

**Comment by rayzeng0221** [comment]
4.25.0就不能正常升级了，这个版本之前的就正常

**Comment by rayzeng0221** [comment]
<img width="1195" alt="截屏2023-02-14 17 19 56" src="https://user-images.githubusercontent.com/16337418/218692527-50d7235b-9d7e-41eb-b38e-33b41cd2638f.png">

**Comment by philips77** [comment]
日志似乎被切断了。 也许单击保存而不是共享并发送文件。

**Comment by rayzeng0221** [comment]
[Log 2023-02-14 17_26_53.txt](https://github.com/NordicSemiconductor/Android-nRF-Connect/files/10730832/Log.2023-02-14.17_26_53.txt)
这就是全部日志了

**Comment by philips77** [comment]
日志的相关部分在这里：
```
A	17:25:58.402	[DFU] Receive Firmware Image request sent
A	17:25:58.452	[DFU] Uploading firmware...
V	17:25:58.452	[DFU] Sending firmware to characteristic 00001532-1212-efde-1523-785feabcd123...
D	17:26:03.566	[Callback] Connection state changed with status: 8 and new state: DISCONNECTED (0)
E	17:26:03.567	Error 8 (0x8): GATT CONN TIMEOUT
I	17:26:03.567	Disconnected
E	17:26:03.592	[DFU] Device has disconnected
D	17:26:03.592	[DFU] gatt.disconnect()
D	17:26:03.592	[DFU] gatt.close()
```
图书馆尝试重复 3 次。
```
A	17:26:11.900	[DFU] Receive Firmware Image request sent
A	17:26:11.925	[DFU] Uploading firmware...
V	17:26:11.925	[DFU] Sending firmware to characteristic 00001532-1212-efde-1523-785feabcd123...
E	17:26:17.085	[DFU] Device has disconnected
D	17:26:17.085	[DFU] gatt.disconnect()
D	17:26:17.085	[DFU] gatt.close()
```
和
```
A	17:26:25.176	[DFU] Receive Firmware Image request sent
A	17:26:25.197	[DFU] Uploading firmware...
V	17:26:25.197	[DFU] Sending firmware to characteristic 00001532-1212-efde-1523-785feabcd123...
E	17:26:30.291	[DFU] Device has disconnected
D	17:26:30.291	[DFU] gatt.disconnect()
D	17:26:30.292	[DFU] gatt.close()
```

也许该设备接受 MTU = 247，但实际上并不支持它？
尝试将设置/nRF5 DFU 选项中的 PRN 更改为 1。
