### ISSUE TITLE
General Question about a data shown in scan result

### ISSUE THREAD

**Issue by ceerqingtingml** [NordicSemiconductor/Android-nRF-Connect#193]
I want to know the meaning of `59ms` marked in red in the attached picture, is it connection interval?

![nrf_san](https://github.com/NordicSemiconductor/Android-nRF-Connect/assets/19239201/0e9c88a4-ea7e-4a00-8522-57edea6b51b8)

**Comment by philips77** [comment]
This is the approximate advertising interval calculated based on timestamps of received advertising packets.

Mind, that all advertising data are sent on 3 advertising channels few ms apart and it is not said which one has been received in one case. Also, getting Scan Response requires sending Scan Request which also prolongs that. Also, some packets may be missed by the phone.
