### ISSUE TITLE
A wristband not discovered by nRF Connect Android

### ISSUE THREAD

**Issue by bordins** [NordicSemiconductor/Android-nRF-Connect#197]
Hi,

I'm developing a BLE proximity detection application, trying to use a variety of devices.  I found that one wristband did not appear in the nRF Connect but the BLE Scanner app could see it.

So, I wonder whether there is any incompatibility issue.  Is there any documentation about this.

Thank you vey much.

**Comment by philips77** [comment]
Hello,
nRF Connect only scans for advertising Bluetooth Low Energy devices. Make sure you device is advertising, i.e. is not advertising directly, in which case Android may not report it to apps. It may advertise directly when it's bonded to try to reconnect with the bonded phone.
Also, check the filter. By default it excludes Apple, Google and Samsung devices, so if the wristband is using one of their UUIDs it may be hidden. Deselect that option in the scan filter.
If you can see the wristband on some, but not all phones, check if the advertising packet is correct. Android 12+(?) may discard wrongly encoded packets, e.g. having additional 0s, etc.
