### ISSUE TITLE
Taking over connection of other app

### ISSUE THREAD

**Issue by vliedel** [NordicSemiconductor/Android-nRF-Connect#21]
When the nRF-Connect app is opened, and I connect to a ble device in my own app, the nRF-Connect takes over the connection: you see it being connected in the nRF-Connect app. Is this intended behaviour?

**Comment by philips77** [comment]
Yes, it's intended. It lets you debug communication (e.g. incoming notifications and indications) from other apps
However, it only does it when you have the GATT server enabled and the Show incoming connections option set in Connectivity settings.

**Comment by vliedel** [comment]
Ok, thanks for the info :)

**Comment by vliedel** [comment]
Hi, after disabling "show incoming connections", I still noticed the nrf connect app took over the connection from my app and kept it connected. Is there some other case in which this can happen?

**Comment by philips77** [comment]
Than I think you have to disable the GATT server in the app. Go to Configure GATT Server and select the Disable (turn off) icon there.

**Comment by vliedel** [comment]
That was disabled already :)

**Comment by philips77** [comment]
With GATT server disabled nRF Connect shouldn't take over connections.
