### ISSUE TITLE
Wrong behavior

### ISSUE THREAD

**Issue by luoyuyi111** [NordicSemiconductor/Android-nRF-Connect#210]
**Describe the bug**
As a ble server, a Read By Type Request is sent immediately after the connection is established

**To Reproduce**
1. Turn on ble adv
2. Another device goes to connect
3. dump hcilog

**Expected behavior**
After the connection is established, the initiator requests a read，but acceptor send a  Read By Type Request.

**Screenshots**
N

**Versions (please complete the following information):**
 - Android version: [13]
 - Phone model [vivo S10]
 - App Version [e.g. 4.28.0]
 - Bluez Version [5.54]

**Additional context**
I think this command can only be sent by the initiator. When the initiator initializes the ATT, this unreasonable behavior results in a Segmentation fault

**Comment by philips77** [comment]
Hello,
Both sides can discover service of the other peer, this is not an issue. 
Also, you may disable automatic service discovery in *Settings -> Connectivity -> Auto service discovery*.
