### ISSUE TITLE
How is "Device type" determined by the scanner?

### ISSUE THREAD

**Issue by chickenoodlestu** [NordicSemiconductor/Android-nRF-Connect#213]
Hi,

I'm working on an ESP32 based BLE project. I recently updated the firmware framework (which included changes to BLE code, at many layers in the stack) and noticed the "Device type" in the nRF Connect scanner changed from "LE only" to "UNKNOWN". I tried sniffing the advertising packets but didn't really notice anything different between before and after the change, so I'd like to know where this information is pulled from so I can investigate whether I need to make some adjustments.

**Comment by philips77** [comment]
This comes from the following call: https://developer.android.com/reference/android/bluetooth/BluetoothDevice#getType()
I have no idea where this is taken from, perhaps some flags in the header. For sure not the advertised data itself.
