### ISSUE TITLE
can not show notify data more than 20 chars

### ISSUE THREAD

**Issue by skyyearxp** [NordicSemiconductor/Android-nRF-Connect#222]
**Describe the bug**
when send a request to mcu, and then mcu notify back 20 chars is ok, when 21 chars there is nothing in log view.

**To Reproduce**
1. connet my mcu device
2. enable notification
3. send request like "test"
4. if notify return is 20 chars, it will be show in log view
5. if notify return more than 20 chars, it will not be seen in log view

**Expected behavior**
all notify return chars will be seen in log view.

**Screenshots**
![image](https://github.com/user-attachments/assets/62145f7f-c861-424f-b058-5147fdbcb8f6)

**Versions (please complete the following information):**
 - Android version: 11
 - Phone model SHARK KSR-A0
 - App Version  4.24.3/4.25.3/4.27.1/4.28.1

**Additional context**
NO

**Comment by skyyearxp** [comment]
after google, i found i need to set  “Request MTU” to Larger Number will be work...

**Comment by philips77** [comment]
You may also find a setting in *Settings / Connectivity / Auto request maximum MTU* so you don't have to do this every time manually.
