### ISSUE TITLE
unable to detect a BLE tag using NRF blinky app

### ISSUE THREAD

**Issue by shreyanshsaxena** [NordicSemiconductor/Android-nRF-Connect#228]
I am unable to detect a BLE tag using NRF blinky app. The tag is visible in the nrf connect app and all the advertising modes are available for that BLE tag.

**Comment by philips77** [comment]
nRF Blinky is scanning for devices that advertise the LED Button Service only.

**Comment by shreyanshsaxena** [comment]
Is there sample code available that I can use as a reference to scan the nearby BLE devices and connect with them?
