### ISSUE TITLE
Automated tests: Extra address variable not interpreted correctly

### ISSUE THREAD

**Issue by McEvilly** [NordicSemiconductor/Android-nRF-Connect#24]
I get the following error when trying to run the sample test. I have tried with different addresses as well.
`test -E EXTRA-ADDRESS 00:00:00:00:00:00 sample_test_hrm.xml
Nordic Semiconductor Automated Tests batch script
Removing old result file...OK
Copying "sample_test_hrm.xml" to /sdcard/Nordic Semiconductor/Test...OK
Starting test service...OK
Test started...OK
Waiting for the result...OK
Result saved in "sample_test_hrm_result.txt".`

`type sample_test_hrm_result.txt
31-10-2016 08:33:52
Version: 4.7.0
Device: Sony E6653, Android version: 6.0.1 (32.2.A.0.305)
Starting 'DFU Test' for 'Upload HRM onto the Dev Kit'
   DFU operation...FAIL:
     - ${EXTRA_ADDRESS} is not a valid Bluetooth low energy address
Starting 'Check basic connectivity of ${EXTRA_ADDRESS}' for 'Basic tests for HRM'
   Connect...FAIL:
     - ${EXTRA_ADDRESS} is not a valid Bluetooth low energy address
Starting 'Remove the bond information' for 'Clean up'
   Unbond...FAIL:
     - ${EXTRA_ADDRESS} is not a valid Bluetooth low energy address`

`adb version
Android Debug Bridge version 1.0.32
Revision eac51f2bb6a8-android`

**Comment by philips77** [comment]
EXTRA_ADDRESS, not EXTRA-ADDRESS in your command.
