### ISSUE TITLE
all mails to you are blocked

### ISSUE THREAD

**Issue by mars3142** [NordicSemiconductor/Android-nRF-Connect#25]
I'm not allowed to send an issue to your mail accounts from Google Mail, because everytime I got a "auth required" error - this also happens to **android-devs**.

![auth required response](https://cloud.githubusercontent.com/assets/220423/20038703/a03eed6e-a438-11e6-80e1-fac20378f3f7.png)

**Comment by philips77** [comment]
Hi, indeed there is something wrong with the server configuration... I'll notify IT dep tomorrow.
Thanks for reporting it.

**Comment by philips77** [comment]
Hi, the mag(at)nordicsemi.no is working now. I'll ask it about the other email tomorrow.

**Comment by philips77** [comment]
Both e-mails should work now. Closing the task. Thanks again for letting us know!
