### ISSUE TITLE
Add write-no-response operation

### ISSUE THREAD

**Issue by simonratner** [NordicSemiconductor/Android-nRF-Connect#33]
Pretty self-explanatory, for writing WRITE_TYPE_NO_RESPONSE characteristics.

**Comment by philips77** [comment]
On the Write dialog select Advanced (v) and there you can switch write types. Write No Respond is Write Command, available only with required property.
For Automated Tests and Macros there is type="..." attr.

**Comment by simonratner** [comment]
Apologies, I wasn't clear. I am specifically talking about automated test
xml scripts.

Do you have an example of this type attr to write to a write-no-response
characteristic? I can't find it in the docs.

**Comment by philips77** [comment]
Oh, sorry. Indeed i forgot to mention. But it's documented in Macros: https://github.com/NordicSemiconductor/Android-nRF-Connect/tree/master/documentation/Macros#write-characteristic
The attribute is the same in AT. I'll update the docs soon.
