### ISSUE TITLE
Android O Support

### ISSUE THREAD

**Issue by JBlaz** [NordicSemiconductor/Android-nRF-Connect#40]
There are some devices that are not picked up by the scan on both my Pixel and Nexus 6P with Android O. The same devices scan just fine with Android Nougat and other Android versions.

**Comment by philips77** [comment]
Could you share the adv packet of those devices obtained on Nougat (raw data or log from nRF Logger)? I'm testing on Pixel with O and don't have such problems.

**Comment by JBlaz** [comment]
![device-2017-07-28-081633](https://user-images.githubusercontent.com/13172076/28721382-5b9f834e-736d-11e7-81c7-53198e66ef42.png)
This device IS visible on a Nougat phone and is not shown on my Pixel running O.

**Comment by philips77** [comment]
Stupid question: you don't have any filter set on Pixel?
Are the scanner setting set to default? (Continuous scanning ON, mode: low latency, offloaded scan batching OFF)

**Comment by JBlaz** [comment]
Definitely not a stupid question but I have no filters set on the pixel.

**Comment by cmmouritsen** [comment]
Any update on this? I am having a similar issue. I have a Moto G (2nd Generation) that is running Marshmallow that picks up my beacon fine in nRF Connect, but on my Nexus 6P running Oreo, nRF doesn't find it. Any suggestions?

**Comment by philips77** [comment]
If a device advertising with invalid data it is ignored by Android O. Invalid data, unfortunately, means also 0s after the last record, which may be a bug on Android. If you have access to a sniffer of to device fw check the adv data and make sure there are only valid EIRs (valid EIR has 1byte for length, 1byte of type and len-1 bytes of data). In theory zeros at the end are ok, but Android ignores such packet.

**Comment by cmmouritsen** [comment]
Thank you, @philips77. My data looks valid to me. Do you see anything that looks off?:

![device-2017-11-10-112419](https://user-images.githubusercontent.com/1235334/32672937-3ce3a904-c60a-11e7-8ae8-e8d0fd521177.png)

**Comment by philips77** [comment]
You don't see those additional data on older Androids. You'd have to use sniffer or debug the fw. Perhaps checking hci log from Android could help if you don't have sniffer. On Developer settings turn on hci snoop log, scan, turn it off and export log to PC. Since Nougat it's inside bug report and can be extracted somehow. Open this log in Wireshark.

**Comment by JBlaz** [comment]
I have learned that on my Pixel 2 running 8.0 I can again scan for these invalid entries. Hopefully this means that in an update the pixel 1 will be able to see them again also. Thank you @philips77 for finding the culprit.
