### ISSUE TITLE
Problem in reliability of receiving advertisements.

### ISSUE THREAD

**Issue by ThomasJFR** [NordicSemiconductor/Android-nRF-Connect#41]
Hello,
I am in the process of designing an app which listens for any BLE advertisements, and filters them according to their contents. Currently, I am testing the reliability of the nordic BluetoothLeScannerCompat - that is, I am seeing if it will receive all advertisement data. I have a peripheral emitting an advertisement on channels 37-39, once every 40ms.

In nRF connect, all of these advertisements are received with great consistency, as shown in the "History" tab of any device. However, when I use the nordic (and Android Standard) Scanner, I am much less consistent in receiving these advertisements. In a 15 second timespan, my application received about 40 advertisements from the peripheral, whereas nRF Connect received about 150.

My code for the scanner:
```
String desiredMacAddress = the peripherals mac address.
BluetoothAdapter mBTAdapter;
BluetoothLeScannerCompat mBleScanner;
ScanCallback scanCallback  = new ScanCallback (){
                @Override
                public void onScanResult(int callbackType, ScanResult result){
                    if ( result.getDevice().getAddress().equals(desiredMacAddress )
                          appendMyTextView("\n You received me!");
                    });
                }
            };

public void init(){
        final BluetoothManager btManager = (BluetoothManager) 
        scanActivity.getSystemService(Context.BLUETOOTH_SERVICE);
        mBTAdapter = btManager.getAdapter();
        mBleScanner = BluetoothLeScannerCompat.getScanner();

        scanLeDevice(true)
}

private void scanLeDevice(final boolean enable){
        if(enable) {
            new Handler().postDelayed(new Runnable() {
                @Override
                public void run() {
                    //BLEDevice Scan has ended
                   stop()
                }
            }, 15000);
            mLeScanner.startScan(scanCallback);
        }
        else{
            mScanning = false;
            mLeScanner.stopScan(scanCallback);
        }
    }

private void stop(){
     scanLeDevice(false)
}
```

Any advice on how to improve scan reliability would be much appreciated!

P.S. I've also posted this to the BluetoothLeScannerCompat github, I

**Comment by philips77** [comment]
You may try setting scan settings in startScan(..,..,..). One of the settings is LOW_LATENCY. Perhaps the default value is Balanced, or something like that?

**Comment by ThomasJFR** [comment]
That is working very well. Still some issues, but I think that is on my end.
Cheers!
