### ISSUE TITLE
How to read request response?

### ISSUE THREAD

**Issue by SapneshNaik** [NordicSemiconductor/Android-nRF-Connect#42]
I am trying develop a custom application for a fitness band which uses Nordic's chip. I can successfully send  notification commands but there are some commands which expect a response back from the band, how can I receive these responses?

For example: an AT+BATT (41:54:2b:42:41:54:54:0d:0a) request makes the band send a battery percentage integer to the official app( Which I found using the hci_logs) How can I read this data in the nRF Connect app?

**Comment by philips77** [comment]
If the data are sent back using notifications you have to enable notifications/indications on the characteristic. There is a (too) small icon with 3/2 arrows pointing down next to the char name if it has Notify/Indicate property. When the notification/indication is received you'll see it in UI and in the log.
