### ISSUE TITLE
How to implement autoconnect in my app

### ISSUE THREAD

**Issue by vineeshvs** [NordicSemiconductor/Android-nRF-Connect#43]
Hi,

We are using nrf51822 for our product. Can I get some documentation of the nRF-Connect app so that we can implement the autoconnect feature in our app?

Is it possible to get a copy of the Android-nRF-Connect app?

Thanks

**Comment by philips77** [comment]
Hi, 
The second argument in `BluetoothDevice#connectGatt(...)` is autoConnect. You may read more about it here: https://devzone.nordicsemi.com/blogs/1046/what-to-keep-in-mind-when-developing-your-ble-andr/
We recommend using the nRF Toolbox's class BleManager: https://github.com/NordicSemiconductor/Android-nRF-Toolbox/blob/master/app/src/main/java/no/nordicsemi/android/nrftoolbox/profile/BleManager.java
There are examples how to use it there in different profiles. If `shouldAutoConnect()` method returns true it will reconnect when the first connection drops with autoConnect set to true. The initial connection is with false as it's much faster.
