### ISSUE TITLE
Wish list: Ability to provide descriptions for custom UUIDs

### ISSUE THREAD

**Issue by nkolban** [NordicSemiconductor/Android-nRF-Connect#45]
When I work with devices that have custom services and characteristics, these have generated UUIDs.  I would love to be able to "describe" these to nRF Connect such that when I view them in the tool, they have more descriptive names.  For example, if we look in the following screen shot, we see "Unknown Service".  I would like to able to provide my own descriptions.  In an ideal world, we would have a database hosted on the Internet that contains a list of services that could be consulted with the ability for users to add/update their own.

![image](https://user-images.githubusercontent.com/3421732/30787106-4b0e99b8-a147-11e7-9dde-3d4282a49905.png)

**Comment by philips77** [comment]
Hi,
You may already do this. Long click a service or a characteristic and select the EDIT icon on the action menu. For characteristics you may also check format=text field so the values are parsed in ASCII.
As to the global database in the Internet, we have it on our backlog. Currently the app does not use Internet permission so it could be safely used by customers with secret projects so we need to make sure the positive pluses overwhelm negative pluses... :)
![device-2017-09-25-095618](https://user-images.githubusercontent.com/6576580/30797895-e05c7b08-a1d7-11e7-804f-92b1be1943ac.png)

**Comment by philips77** [comment]
In the navigation drawer you\ll also find a menu item "Definitions" where you'll find all your custom name + those defined by SIG or other known to the nRF Connect. You may share the definitions between youy phones. The definitions file is also compatible with nRF Connect for PC.
