### ISSUE TITLE
Timeout on android 7.1.1

### ISSUE THREAD

**Issue by mahanoob** [NordicSemiconductor/Android-nRF-Connect#48]
It's able to connect BLE without any problem but gatt timeout error while discovering the services on Android 7.1.1

**Comment by philips77** [comment]
This seems to be an issue either with the device you are trying to connect or your phone. Did you try another phone? If you have problems with developing your device firmware, please ask a question on DevZone. I'll close this issue here as this is not related to the nRF Connect.
