### ISSUE TITLE
Not Opening in Android Studio

### ISSUE THREAD

**Issue by VinayTShetty** [NordicSemiconductor/Android-nRF-Connect#53]
**Hi i extracted the zip file of Android-nRF-Connect,But its not opening in android studio.
Have attached the Screen shot 
ScreenShot1 -->ExtractedFolder.
ScreenShot2 --->Inside ExtractedFolder.
AndroidStudio_ScreetShot --->Its not Showing the symbol of android studio to open.**
![androidstudio_screenshot](https://user-images.githubusercontent.com/33421892/34638835-2b56ae9e-f2fa-11e7-86e4-c8395e22ef49.PNG)
![screenshot1](https://user-images.githubusercontent.com/33421892/34638836-2b8057b2-f2fa-11e7-8a03-82a578398709.PNG)
![screenshot2](https://user-images.githubusercontent.com/33421892/34638837-2ba91490-f2fa-11e7-8e5a-9f3ff84ac827.PNG)

**Comment by philips77** [comment]
That's true. As stated on the Readme, the source code of this as it's not available. On GitHub there is just some documentation.

**Comment by VinayTShetty** [comment]
@philips77 
@roshanrajaratnam 
Can u please Provide any source code link which will send/Receive command to BLE.
Am running in loops,As of now i have found only Scan,Connect,and Read Charcterstics.
I want the source code which will Send some commands to BLE.
It would be a Great Help,Thanks in advance.

**Comment by philips77** [comment]
Check out https://github.com/NordicSemiconductor/Android-nRF-Blinky. This is a good project to start with BLE on Android. This project also depends on the Android-Ble-Library, like Toolbox.

**Comment by philips77** [comment]
You'll find there BlinkyManager (https://github.com/NordicSemiconductor/Android-nRF-Blinky/blob/master/app/src/main/java/no/nordicsemi/android/blinky/profile/BlinkyManager.java) class which does what you need.

**Comment by VinayTShetty** [comment]
@philips77 
Thank you for Providing the link.
But i have few Error after opening in android Studio Can u provide some guidance on Resolving it.
ScreenShot1 -->After Extracting zip file
ScreenShot2 -->Inside Android-nRF-Blinky-master
AndroidStudio_ScreenShot -->Showing the error.
![androidstudio_screenshot](https://user-images.githubusercontent.com/33421892/34639072-d003c9fa-f2fe-11e7-9b9e-dbba92e093ef.PNG)
![screenshot1](https://user-images.githubusercontent.com/33421892/34639073-d02e0076-f2fe-11e7-8e48-4e466874563a.PNG)
![screenshot2](https://user-images.githubusercontent.com/33421892/34639074-d057499a-f2fe-11e7-9608-95a468691a8c.PNG)

**Comment by philips77** [comment]
Try opening first the Ble-library project only in the AS. It will create all required iml files. Then ensure your settings.gradle file in the Blinky project the same as here: https://github.com/NordicSemiconductor/Android-nRF-Blinky/blob/master/settings.gradle.
In this settings file there should be a path to the ble.iml file that was created in the first step.

**Comment by VinayTShetty** [comment]
I deleted the entire Project and extracted the zip file.
Am unable to find the Ble-library project folder.
![screenshot1](https://user-images.githubusercontent.com/33421892/34639307-a0789012-f303-11e7-88e6-343336065703.PNG)
![screenshot2](https://user-images.githubusercontent.com/33421892/34639308-a0a77d0a-f303-11e7-8b1e-9c58bd7f1402.PNG)

**Comment by VinayTShetty** [comment]
@philips77 
I checked in Setting also.But the issue is not yet resolved.
![androidstudio_screenshot](https://user-images.githubusercontent.com/33421892/34639388-68e71176-f305-11e7-842d-f99e68e3370e.PNG)

**Comment by philips77** [comment]
Just like in nRF Toolbox, you have to clone the Android-BLE-Library project from GitHub, ensure the folder name is equal Android-BLE-Library, import it to Android Studio, then clone the nRF Blinky project to the same folder as you cloned the library and import as well it to AS. You had it correctly before, just had to import the library project, as I wrote.
