### ISSUE TITLE
Characheristic Value Representation

### ISSUE THREAD

**Issue by Skodra** [NordicSemiconductor/Android-nRF-Connect#58]
I think it would only be adequate to take in account _Unit_ value of the _Characteristic Presentation Format_ descriptor and base on that format the _Value_ field of the characteristic. Example,  I have set all _Characteristic Presentation Format_ fields accordingly  but _nRF Connect_ would not display value of characteristic as unsigned 16-bit integer.
![image](https://user-images.githubusercontent.com/11903296/38223029-e1955d36-36e8-11e8-8274-c5fb1573921f.png)
Issue posted here also https://devzone.nordicsemi.com/f/nordic-q-a/31253/is-it-possible-to-display-integer-on-nrf-connect-app

**Comment by philips77** [comment]
Fixed in 4.19 :)

**Comment by Skodra** [comment]
Thanks for the quick response! Was this already in you plans?

**Comment by philips77** [comment]
No, but it was a fairly small but useful feature, so we decided to go with it quickly. Hope it works well.
