### ISSUE TITLE
Automated tests: String assertion fails incorrectly

### ISSUE THREAD

**Issue by NikBrg** [NordicSemiconductor/Android-nRF-Connect#60]
I have an `<assert-value value-string="GB"/>` check inside a `<read>`. In the logs, I see the following:

```
Read response received from ..., value: (0x) 47-42-00
Asserting characteristic value...
Value of the characteristic 'GB' is not equal to 'GB'
```

Any idea why the assertion is failing even though it seems to receive the correct data?

**Comment by philips77** [comment]
There is a 00 at the end. "GB" has just 2 bytes, but 3 we received.

**Comment by NikBrg** [comment]
Ok thank you! How do I add the string terminator 0x00 in the XML file? At the moment the assert looks as follows:

`<assert-value description="Check country" value-string="GB" />`

**Comment by philips77** [comment]
Well... You may do
```<assert-value description="Check country" value="474200" />```

**Comment by NikBrg** [comment]
This is what I wanted to avoid... Does that mean the string assertion `value-string`  cannot be used as documented?

**Comment by philips77** [comment]
If the value returned wouldn't be null-terminated then it would work. I can 'fix' it (add support for null-terminated during values) in the next release.

**Comment by NikBrg** [comment]
Thank you, that would be great! Actually the only reason we are using string assertions is, because we are only interested in the data before the null termination (and not afterwards).

**Comment by philips77** [comment]
So it may be that you have more non-zero bytes there and just want to check 'until 00'?

**Comment by philips77** [comment]
Just write some examples that you'd like to have in the test. I'll come back to it before next release.
