### ISSUE TITLE
Possible bluetooth stack corruption

### ISSUE THREAD

**Issue by andres7293** [NordicSemiconductor/Android-nRF-Connect#62]
Hi.
Using the nrf connect app with Huawei mya-L11. Under certain actions, the phone needs to be restarted in order to work again.
Here are the steps:
1. Open nrf connect.
2. Scan devices.
3. Connect to desired device. 
4. Turn off bluetooth and wait few seconds.
5. Turn on bluetooth.
5. Try to connect again with device.
6. Can't connect to device anymore.

At this moment, the phone needs to be restarted to work again.
The screenshot below shows the error.

Thanks !!!.
![screenshot_2018-04-26-10-39-43](https://user-images.githubusercontent.com/20456230/39298722-dfd32196-493e-11e8-832d-0ad24e730132.png)

**Comment by andres7293** [comment]
Hi again.
Doing the same process previously explained. When device can't connect, going to Bluetooth settings and doing bonding process with device, independently of the result, opening nrf connect again, the connection has been established without user interaction.

This seems Android bug, rather than Nordic application.

**Comment by philips77** [comment]
Yes, looks like an Android bug or a bug in your phone's controller. Try a different phone.
