### ISSUE TITLE
GATT uint32 write fails for 2^31 < n < 2^32

### ISSUE THREAD

**Issue by tvdstaaij** [NordicSemiconductor/Android-nRF-Connect#64]
App version: 4.19.0
Android version: 8.1.0

Steps to reproduce:

1. Connect to device
2. Open write dialog for a 4-byte attribute
3. Select type UINT32
4. Attempt to submit a value larger than 2^31 but lower than 2^32, e.g. 2147483649

Expected: app writes the value
Actual: error message "This value does not match its type."

In addition, it seems that once this error is triggered it doesn't go away even when a lower value is entered.

**Comment by philips77** [comment]
Thanks. I'll look into that. That of course is because int in Java is signed 32 bits...

**Comment by philips77** [comment]
Fixed internally.
