### ISSUE TITLE
连接不上设备

### ISSUE THREAD

**Issue by kangshaopeng** [NordicSemiconductor/Android-nRF-Connect#65]
连接上设备之后，把蓝牙关闭再打开蓝牙，点击连接设备连接不上，必须重新回到扫描页面，扫描设备才可以连接上

**Comment by Domvel** [comment]
@kangshaopeng In english please 😄

**Comment by philips77** [comment]
He mentioned, that after resetting Bluetooth you have to go back to scanning, scan the device and than you're able to reconnect. That's known issue with Android. Please, read about it here: https://devzone.nordicsemi.com/b/blog/posts/what-to-keep-in-mind-when-developing-your-ble-andr 
Android assumes a public address when such never was scanned before, so connect request will be ignored by the device when it has a private tour of address.

**Comment by kangshaopeng** [comment]
ok,thanks
