### ISSUE TITLE
Pixel XL running Android 8.1 not detecting any BLE devices during scan

### ISSUE THREAD

**Issue by zgmfx** [NordicSemiconductor/Android-nRF-Connect#66]
There are many BLE devices in the area but the nRF Connect app (v 4.19.1)  is not detecting any of them during scan.   Running the same version of the app on another phone (Nexus 5, Android 6.0.1) in the same area has no issues detecting BLE devices.  This app used to work fine on the Pixel XL and properly detect devices.  I'm not sure if it was an update to the App or an Android update which broke the scan.

**Comment by philips77** [comment]
Try resetting the phone. It's a BLE issue on the phone.

**Comment by zgmfx** [comment]
Ah yes, rebooting the phone made it work again.  Thanks.
