### ISSUE TITLE
Auto-select text input when CPF descriptor with UTF-8 is present

### ISSUE THREAD

**Issue by carlescufi** [NordicSemiconductor/Android-nRF-Connect#82]
When a Characteristic contains a Characteristic Presentation Format that contains UTF-8 as its value, nRF Connect Should switch to text input instead of hex, since the contents of the characteristic value are supposed to be UTF-8 encoded text.

CC @mostafaberg @jovirus @roshanrajaratnam @philips77

CC @jhedberg

**Comment by philips77** [comment]
Easy. Had you written this 1h earlier, you'd have had it in the released that just went public :)

**Comment by philips77** [comment]
The problem is with other values of this descriptor. Why utf8 will have a string input while other values a generic one. But I understand your use case. Let's say this is the most common.

**Comment by philips77** [comment]
Released in version 4.20.2.
