### ISSUE TITLE
nRF Connect v.4.21.0  can't discoverServices

### ISSUE THREAD

**Issue by hackill** [NordicSemiconductor/Android-nRF-Connect#86]
With the latest version of app 4.21.0, I found that my device could not find the service and was stuck at 'gatt. DiscoverServices ()'. Then I used the v4.20.0 throw again and couldn't work. Then I used an early version of 4.14.2 to work properly.

I also have another ble product, which works fine on 4.21.0.

**Comment by philips77** [comment]
There were no changes in this part of the app, as far as I remember. Try restarting Bluetooth or the phone and it should work with 4.21 as well. If it doesn't help, could you past here logs from the app?

**Comment by hackill** [comment]
okey  wait
