### ISSUE TITLE
Procedure to use this API

### ISSUE THREAD

**Issue by VinayTShetty** [NordicSemiconductor/Android-nRF-Connect#88]
Hi ,
Can you  please provide the link on how to setup this API in android studio.
I download ed this API and opened in android studio it's nothing is showing.

**Comment by philips77** [comment]
The source code of nRF Connect is not public. This repo contains only the documentation.

**Comment by VinayTShetty** [comment]
Can you please provide any BLE stable application code link for developing android application.
It would be helpful
