### ISSUE TITLE
scan results differents with the same devices around

### ISSUE THREAD

**Issue by gerisse** [NordicSemiconductor/Android-nRF-Connect#91]
hello
not really a bug , i hope, but i dont undestand it :
when i scan my environment, i don't see the same devices that i find with my scan computer (with blueman-manager). You can see this in the picture below :
![img_000](https://user-images.githubusercontent.com/10636735/51526632-1706d580-1e33-11e9-8366-4c088292daa9.jpg)
it likes there is a mutually exclusion. Strange.
an idea ? Thanks . Gerisse

**Comment by philips77** [comment]
I guess your PC displays the Classic Bluetooth devices while nRF Connect only Bluetooth LE devices.
Audio devices usually use the Classic Bluetooth technology, as it allows to transmit data with a higher throughput.
