### ISSUE TITLE
Clear log icon is invisible in portrait screen mode

### ISSUE THREAD

**Issue by isyq** [NordicSemiconductor/Android-nRF-Connect#93]
**Describe the bug**
At the bottom of log panel, the bar contains four icons: copy, save, share and clear.
In portrait mode, the rightmost 'clear' icon is invisible in my phone, with the screen resolution: 3120 x 1440.
In landscape mode, this icon is visible.

**To Reproduce**
1. Connect a BLE peripheral
2. Right slip to open log panel
3. View the icons at the bottom of log panel
4. The rightmost icon(clear icon) is invisible

**Expected behavior**
All icons should be visible. Or a 'more' icon should be added to display all available icons.

**Screenshots**
Two screenshots at below. One is for landscape which is OK. The other is portrait, not good.

**Versions (please complete the following information):**
 - Android version: [e.g. 9.0.0]
 - Phone model [e.g. Huawei Mate 20 Pro]
 - App Version [e.g. 4.22.3]

![landscape](https://user-images.githubusercontent.com/7067361/53621245-e6376e80-3c30-11e9-8338-f96eb748d4ad.jpg)
![portrait](https://user-images.githubusercontent.com/7067361/53621246-e6d00500-3c30-11e9-9dab-c36954232c6f.jpg)

**Comment by philips77** [comment]
Hello,
Thanks for reporting this bug. I have seen it on some of our phones as well. I will fix it in the new release.

**Comment by philips77** [comment]
Fixed internally.
