### ISSUE TITLE
Company Id not resolving

### ISSUE THREAD

**Issue by abhijits3** [NordicSemiconductor/Android-nRF-Connect#94]
When scanning a ble device company id allocated shows up as reserved id and does not resolve to the company name. This happens for all company ids after serial number 1785 in the company id list on Bluetooth SIG

**Comment by philips77** [comment]
Yes, I update the ids from time to time. They are hardcoded in the app, as it doesn't use the Internet. I'll update the list on the next release.

**Comment by philips77** [comment]
Fixed internally.
