### ISSUE TITLE
NRF Connect Android

### ISSUE THREAD

**Issue by mahbubiftekhar** [NordicSemiconductor/Android-nRF-Connect#95]
Hi

Is the code for this app publicly available? 

https://play.google.com/store/apps/details?id=no.nordicsemi.android.mcp

Thanks

**Comment by philips77** [comment]
No, it's not, as written in the main Readme page.
We provide code for out other apps and libraries, if you need a starting point for your project. Check out BLE Library and Android Scanner Compat Library, or nRF Toolbox or nRF Blinky apps on our GitHub page.
