### ISSUE TITLE
Title is "A public API for the nRF Connect for Android"

### ISSUE THREAD

**Issue by Artyrm** [NordicSemiconductor/Android-nRF-Connect#97]
So, what's actually API here?

**Comment by philips77** [comment]
nRF Connect has 2 sevices that can be started using `adb`, one does the automated testing and another can trigger DFU update. The bat scripts that can be used to start them are on GitHub and also copied to SD card to Nordic Semiconductor folder. Here on GitHub you will find the documentation how to use it + documentation about Macros.
But I agree, the subtitle can be changed :)
